name: Hardcore
version: 1.0
main: ca.bungo.hardcore.hardcore.Hardcore
depend: [Core, GriefPrevention]
api-version: 1.13
commands:
  revive:
    usage: /revive <player>
  perks:
    usage: /perks
  shop:
    usage: /shop
  items:
    usage: /items
  bounty:
    usage: /bounty
  teams:
    usage: /teams
  help:
    usage: /help
  test:
    usage: /test
  tpa:
    usage: /tpa
    aliases: [tpaccept, tpdeny, tpr]
  home:
    usage: /home
    aliases: [sethome, delhome, homes]
  stats:
    usage: /stats